import { govPoolABI } from '../abi';

export const bscStakePools = [
  {
    id: 'bifi-tff',
    name: 'SWGB',
    logo: 'single-assets/BIFI.png',
    token: 'SWGB',
    tokenDecimals: 18,
    tokenAddress: '0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb',
    tokenOracle: 'pancake',
    tokenOracleId: 'BIFI',
    earnedToken: 'TFF',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0x2d69c55baEcefC6ec815239DA0a985747B50Db6E',
    earnContractAddress: '0xD715f4b7D08dae3c9CF038dC07913A2aE37c23c5',
    earnContractAbi: govPoolABI,
    earnedOracle: 'pancake',
    earnedOracleId: 'WBNB',
    partnership: false,
    status: 'active',
    hideCountdown: false,
    partner: {
      logo: 'stake/beefy/tff.svg',
      background: 'stake/beefy/background.png',
      text:
        "Tutti Frutti Finance",
      website: 'https://tuttifrutti.finance/',
      social: {
        telegram: 'https://t.me/TuttifruttiFi',
        twitter: 'https://twitter.com/TuttifruttiFi',
      },
    },
  },

  {
    id: 'bifi-bnb',
    name: 'SWGB',
    logo: 'single-assets/BIFI.png',
    token: 'SWGB',
    tokenDecimals: 18,
    tokenAddress: '0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb',
    tokenOracle: 'pancake',
    tokenOracleId: 'BIFI',
    earnedToken: 'BNB',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    earnContractAddress: '0x9CBce88c77DA23d5DC5Ae18580b5f5AaBc3a9A73',
    earnContractAbi: govPoolABI,
    earnedOracle: 'pancake',
    earnedOracleId: 'WBNB',
    partnership: false,
    status: 'active',
    hideCountdown: true,
    partner: {
      logo: 'stake/beefy/beefyfinance.png',
      background: 'stake/beefy/background.png',
      text:
        "Swirge is focused on building decentralized products, to decentralize social media, e-commerce, and finance. Swirge Finance is a Yield Optimizer and Staking Platform built on the Binance Smart Chain with Multi-chain support ( Avalanche and Huobi Eco Chain ). Swirge has its own token. Swirge tokens exist both on the Ethereum blockchain as ($SWG) and on the Binance Smart Chain as ($SWGb). Everyone who holds our own $SWGb token can create and vote on proposals, they also get a share of all harvests done, every hour, every day on all our vaults. That's a lot of BNB that goes straight to our $SWGb holders. All you have to do is stake your $SWGb in this vault, it’s that simple, come back and harvest your BNB whenever you need it! (You can still vote on proposals even though you have staked your $SWGb here).",
      website: 'https://finance.swirge.com',
      social: {
        telegram: 'http://t.me/swirgepay',
        twitter: 'https://twitter.com/swirgenetwork',
      },
    },
  },

  {
    id: 'bifi-juld',
    name: 'SWGB',
    logo: 'single-assets/BIFI.png',
    token: 'SWGB',
    tokenDecimals: 18,
    tokenAddress: '0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb',
    tokenOracle: 'pancake',
    tokenOracleId: 'BIFI',
    earnedToken: 'JULD',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0x5A41F637C3f7553dBa6dDC2D3cA92641096577ea',
    earnContractAddress: '0x68f1a7ACC14F71E885Be66a1171F71A4470DD231',
    earnContractAbi: govPoolABI,
    earnedOracle: 'pancake',
    earnedOracleId: 'JULD',
    partnership: false,
    status: 'active',
    hideCountdown: true,
    partner: {
      logo: 'stake/beefy/beefyfinance.png',
      background: 'stake/beefy/background.png',
      text:
        "Swirge is focused on building decentralized products, to decentralize social media, e-commerce, and finance. Swirge Finance is a Yield Optimizer and Staking Platform built on the Binance Smart Chain with Multi-chain support ( Avalanche and Huobi Eco Chain ). Swirge has its own token. Swirge tokens exist both on the Ethereum blockchain as ($SWG) and on the Binance Smart Chain as ($SWGb). Everyone who holds our own $SWGb token can create and vote on proposals, they also get a share of all harvests done, every hour, every day on all our vaults. That's a lot of BNB that goes straight to our $SWGb holders. All you have to do is stake your $SWGb in this vault, it’s that simple, come back and harvest your BNB whenever you need it! (You can still vote on proposals even though you have staked your $SWGb here).",
      website: 'https://finance.swirge.com',
      social: {
        telegram: 'http://t.me/swirgepay',
        twitter: 'https://twitter.com/swirgenetwork',
      },
    },
  },

  {
    id: 'bifi-cake',
    name: 'SWGB',
    logo: 'single-assets/BIFI.png',
    token: 'SWGB',
    tokenDecimals: 18,
    tokenAddress: '0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb',
    tokenOracle: 'pancake',
    tokenOracleId: 'BIFI',
    earnedToken: 'CAKE',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82',
    earnContractAddress: '0xAed559D484A4F40896196e02bD378E8eE1E4d0Ae',
    earnContractAbi: govPoolABI,
    earnedOracle: 'pancake',
    earnedOracleId: 'WBNB',
    partnership: false,
    status: 'active',
    hideCountdown: true,
    partner: {
      logo: 'stake/beefy/beefyfinance.png',
      background: 'stake/beefy/background.png',
      text:
        "Swirge is focused on building decentralized products, to decentralize social media, e-commerce, and finance. Swirge Finance is a Yield Optimizer and Staking Platform built on the Binance Smart Chain with Multi-chain support ( Avalanche and Huobi Eco Chain ). Swirge has its own token. Swirge tokens exist both on the Ethereum blockchain as ($SWG) and on the Binance Smart Chain as ($SWGb). Everyone who holds our own $SWGb token can create and vote on proposals, they also get a share of all harvests done, every hour, every day on all our vaults. That's a lot of BNB that goes straight to our $SWGb holders. All you have to do is stake your $SWGb in this vault, it’s that simple, come back and harvest your BNB whenever you need it! (You can still vote on proposals even though you have staked your $SWGb here).",
      website: 'https://finance.swirge.com',
      social: {
        telegram: 'http://t.me/swirgepay',
        twitter: 'https://twitter.com/swirgenetwork',
      },
    },
  },

  {
    id: 'bifi-lead',
    name: 'SWGB',
    logo: 'single-assets/BIFI.png',
    token: 'SWGB',
    tokenDecimals: 18,
    tokenAddress: '0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb',
    tokenOracle: 'pancake',
    tokenOracleId: 'BIFI',
    earnedToken: 'LEAD',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0x2ed9e96EDd11A1fF5163599A66fb6f1C77FA9C66',
    earnContractAddress: '0x7f38E3F4c7e236b2A9eb22fAa6a7756E3e7b1A54',
    earnContractAbi: govPoolABI,
    earnedOracle: 'pancake',
    earnedOracleId: 'LEAD',
    partnership: false,
    status: 'active',
    hideCountdown: true,
    partner: {
      logo: 'stake/beefy/beefyfinance.png',
      background: 'stake/beefy/background.png',
      text:
        "Swirge is focused on building decentralized products, to decentralize social media, e-commerce, and finance. Swirge Finance is a Yield Optimizer and Staking Platform built on the Binance Smart Chain with Multi-chain support ( Avalanche and Huobi Eco Chain ). Swirge has its own token. Swirge tokens exist both on the Ethereum blockchain as ($SWG) and on the Binance Smart Chain as ($SWGb). Everyone who holds our own $SWGb token can create and vote on proposals, they also get a share of all harvests done, every hour, every day on all our vaults. That's a lot of BNB that goes straight to our $SWGb holders. All you have to do is stake your $SWGb in this vault, it’s that simple, come back and harvest your BNB whenever you need it! (You can still vote on proposals even though you have staked your $SWGb here).",
      website: 'https://finance.swirge.com',
      social: {
        telegram: 'http://t.me/swirgepay',
        twitter: 'https://twitter.com/swirgenetwork',
      },
    },
  },

  {
    id: 'bifi-safep',
    name: 'SAFEP',
    logo: 'single-assets/BIFI.png',
    token: 'SWGB',
    tokenDecimals: 18,
    tokenAddress: '0xe40255c5d7fa7ceec5120408c78c787cecb4cfdb',
    tokenOracle: 'pancake',
    tokenOracleId: 'BIFI',
    earnedToken: 'SAFEP',
    earnedTokenDecimals: 18,
    earnedTokenAddress: '0xA8c514D991F59baB02d32b68f04204cB89261c88',
    earnContractAddress: '0x5342A93851AA202b24A8Fa5f155db9299c2036Ca',
    earnContractAbi: govPoolABI,
    earnedOracle: 'pancake',
    earnedOracleId: 'SAFEP',
    partnership: true,
    status: 'active',
    hideCountdown: false,
    partner: {
      logo: 'stake/beefy/safeprotocol.png',
      background: 'stake/beefy/background.png',
      text:
        "A First Blockchain Socio-Political Media Platform that supports community building, poverty alleviation and reduction, voting, economic growth, basic social and economic needs and sustainment of a democratic and all-inclusive society thus allowing social interaction amongst citizens and politicians with cryptocurrency rewards.",
      website: 'https://safeprotocol.io/',
      social: {
        telegram: 'https://t.me/SafeProtocolGlobal/',
        twitter: 'https://twitter.com/SafeProtocol/',
      },
    },
  },
];
